### ISSUE TITLE
pyuv doesn't compile with Python 3.10

### ISSUE THREAD

**Issue by larryhastings** [saghul/pyuv#273]
There are warnings about deprecated functions, etc.  But the one compilation error:

    In file included from src/pyuv.c:8: 
    src/handle.c: In function ‘resurrect_object’:
    src/handle.c:17:21: error: lvalue required as left operand of assignment
       17 |     Py_REFCNT(self) = refcnt;
          |                     ^

I call shenanigans!

**Comment by saghul** [comment]
Hey there! Alas I no longer have many cycles to maintain this package. Also, that logic to resurrect objects probably scares many :-/ If you can come up with a patch I'd be happy to apply it.

**Comment by bjornfor** [comment]
I think this is a duplicate of https://github.com/saghul/pyuv/issues/271. (That issue even has a proposed fix in the description.)
