### ISSUE TITLE
error AttributeError: 'pyuv._cpyuv.Signal' object has no attribute 'unref'

### ISSUE THREAD

**Issue by deivymg** [saghul/pyuv#258]
im working on pyuv 1.4.0.  and getting AttributeError: 'pyuv._cpyuv.Signal' object has no attribute 'unref'.

im following a tutorial for tls connection using  uvtls.py.

**Comment by saghul** [comment]
That example is years old, it would need to be brought up to date.
